# This file is a template, and might need editing before it works on your project.
# Official docker image.
image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]


before_script:
  - export DOCKER_HOST="tcp://localhost:2375"
#  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    #- export DOCKER_HOST="tcp://localhost:2375"
    #- docker build --network host --pull  -t "$CI_REGISTRY_IMAGE" .
    #- docker push "$CI_REGISTRY_IMAGE"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE

  only:
    - master
    
build-master-arm64:
  stage: build
  image: docker:dind
  tags: 
    - aarch64
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --network host --pull  -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    #- echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    #- /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE

  only:
    - master

