version: '3'

services:
  xbar:
    build: .
    ports:
      - "8083:8083"
    working_dir: /node/
    entrypoint: crossbar start --cbdir /node/.crossbar --config /node/.crossbar/config.json

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379

  helper:
    build: .
    entrypoint: pypy3 /node/components/lambents/lib/helpers.py
    working_dir: /node/components
    restart: on-failure
    depends_on:
      - xbar
    environment:
      - PYTHONPATH=/node
      - XBAR_ROUTER=ws://xbar:8083/ws

  scan_8266:
    build: .
    entrypoint: pypy3 /node/components/scan_77778266.py
    working_dir: /node/components
    restart: on-failure
#    network_mode: "bridge"
    depends_on:
      - xbar
    environment:
      - PYTHONPATH=/node
      - XBAR_ROUTER=ws://xbar:8083/ws
      - LA4_REDIS=redis
  machine:
    build: .
    entrypoint: pypy3 /node/components/lambents/lib/machine.py
    working_dir: /node/components
    restart: on-failure
    depends_on:
      - xbar
    environment:
      - PYTHONPATH=/node
      - XBAR_ROUTER=ws://xbar:8083/ws
      - LA4_CONFIG_PATH=../default.yml
  link:
    build: .
    entrypoint: pypy3 /node/components/lambents/routing/links.py
    working_dir: /node/components
    restart: on-failure
    depends_on:
      - xbar
    environment:
      - PYTHONPATH=/node
      - XBAR_ROUTER=ws://xbar:8083/ws