FROM crossbario/crossbar:pypy-arm64v8

USER root
RUN apt-get update && apt-get install -y rustc cargo netcat && rm -rf ~/.cache && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /node
RUN pip install --no-cache-dir -r requirements.txt
COPY . /node
RUN chown -R crossbar:crossbar /node/*
#USER crossbar

ENTRYPOINT ["crossbar", "start", "--cbdir", "/node/.crossbar"]
